name: Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Run tests with JUnit
      run: mvn test

    - name: Build with Apache Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: target/*.jar
        name: Release ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
