name: Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Build with Apache Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
